### ISSUE TITLE
The software flashes back after a short while.

### ISSUE THREAD

**Issue by devyujie** [kannagi0303/yt-dlp-gui#52]
https://user-images.githubusercontent.com/48620527/211761772-d16d33c1-9cb3-4bb5-bce0-6932a8fa6731.mp4

**Comment by kannagi0303** [comment]
您好，这原因很可能与过去回报过的issus有关。
是由于软件没有在此文件夹中写入的权限而闪退。
可以尝试将软件放在有写入权限的文件夹中

Hello, this reason is probably related to the issus reported in the past.
It crashes because the software does not have permission to write in this folder.
You can try to put the software in a folder with write permissions

**Comment by devyujie** [comment]
> 您好，这原因很可能与过去回报过的issus有关。 是由于软件没有在此文件夹中写入的权限而闪退。 可以尝试将软件放在有写入权限的文件夹中
> 
> Hello, this reason is probably related to the issus reported in the past. It crashes because the software does not have permission to write in this folder. You can try to put the software in a folder with write permissions

Thanks, fixed it, great job!

**Comment by kannagi0303** [comment]
我发布了新的版本了，现在当遇到没有权限时依旧可以执行，差别在无法储存设定值，如果您有兴趣可以尝试一下新版本

I have released a new version now. Even if there is no permission, it can still be executed. The difference is that the settings cannot be saved. If you are interested, you can try the new version.

**Comment by WeaselOnaStick** [comment]
I still get this issue even though I downloaded 2023.03.28 version just now. For a split second while I could see the window, I saw that the default path field on the bottom had a folder that doesn't exist. (somehow with my irl name in there)
